-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 19:14:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culinary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culinary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culinary` DEFAULT CHARACTER SET utf8 ;
USE `culinary` ;

-- -----------------------------------------------------
-- Table `culinary`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`group` ;

CREATE TABLE IF NOT EXISTS `culinary`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`user` ;

CREATE TABLE IF NOT EXISTS `culinary`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NULL DEFAULT 1,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `avatar_url` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `culinary`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`recipe` ;

CREATE TABLE IF NOT EXISTS `culinary`.`recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `ingredients` LONGTEXT NOT NULL,
  `portion` DECIMAL(2,2) NULL,
  `preparation` LONGTEXT NULL,
  `adicional_information` LONGTEXT NULL,
  `cooking_hours` FLOAT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_recipe_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `culinary`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`category` ;

CREATE TABLE IF NOT EXISTS `culinary`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`recipe_has_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`recipe_has_category` ;

CREATE TABLE IF NOT EXISTS `culinary`.`recipe_has_category` (
  `recipe_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `category_id`),
  INDEX `fk_recipe_has_category_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_recipe_has_category_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_has_category_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `culinary`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `culinary`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`avaliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`avaliation` ;

CREATE TABLE IF NOT EXISTS `culinary`.`avaliation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coment` TEXT NOT NULL,
  `stars` TINYINT(1) NOT NULL,
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_avaliation_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_avaliation_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `culinary`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliation_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `culinary`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`favorite` ;

CREATE TABLE IF NOT EXISTS `culinary`.`favorite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_favorite_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_favorite_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `culinary`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `culinary`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`file` ;

CREATE TABLE IF NOT EXISTS `culinary`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_path` TEXT NOT NULL,
  `type` ENUM('Image', 'Video') NOT NULL,
  `recipe_id` INT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_file_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_file_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_file_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `culinary`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `culinary`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`permission` ;

CREATE TABLE IF NOT EXISTS `culinary`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`group_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`group_has_permission` ;

CREATE TABLE IF NOT EXISTS `culinary`.`group_has_permission` (
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `permission_id`),
  INDEX `fk_group_has_permission_permission1_idx` (`permission_id` ASC) VISIBLE,
  INDEX `fk_group_has_permission_group1_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_has_permission_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `culinary`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `culinary`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culinary`.`user_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culinary`.`user_token` ;

CREATE TABLE IF NOT EXISTS `culinary`.`user_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `refresh_token` LONGTEXT NOT NULL,
  `expires_date` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_token_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_token_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `culinary`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
