version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=culinary_user
      - MYSQL_PASSWORD=culinary_password
      - MYSQL_DATABASE=culinary_db
      - DATABASE_URL=mysql://culinary_user:culinary_password@mysql:3306/culinary_db
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_culinary_password
      MYSQL_USER: culinary_user
      MYSQL_PASSWORD: culinary_password
      MYSQL_DATABASE: culinary_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
